development:
  adapter: postgresql
  encoding: unicode
  database: yearbooker_development
  pool: 5
  username: peterlai
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: yearbooker_test
  pool: 5
  username: peterlai
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: yearbooker_production
  pool: 5
  username: peterlai
  password:
